name: literacy_game
description: "An offline-first literacy learning game."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  characters: ^1.4.1
  collection: ^1.19.1
  flame: ^1.38.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_soloud: ^4.0.13
  flutter_svg: ^2.2.3
  http: ^1.6.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/data/
    - assets/audio/letter_dragging/
    - assets/audio/sentences/
    - assets/audio/ugandan_animals/
    - assets/audio/alphabet_objects/
    - assets/audio/alphabet/
    - assets/images/
    - assets/images/alphabet_objects/
    - assets/images/ugandan_animals/
    - assets/images/sentence_building/
    - assets/images/lives/
    - assets/images/area_menu/
    - assets/images/balance_game/
    - assets/images/logic_game/
